spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://avijithait9762:SoY2vgZdz1kHPchK@cluster0.emxfi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
# Enable logging to file (default: logs/spring.log)
logging.file.name=application.log

# OR specify a directory (logback will create spring.log inside it)
#logging.file.path=./logs

# Optional: log pattern
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n
#Email Config
#spring.mail.host=smtp.gmail.com
spring.mail.host=smtp.zoho.in
spring.mail.port=587
#spring.mail.username=avijithait9762@gmail.com
spring.mail.username=avijithait@zohomail.in
#spring.mail.password=mzxv pafz uyfm asvx
spring.mail.password=2hNcPTfYML2z


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.debug=true






